apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-package-repo
  namespace: tanzu-package-repo
spec:
  fetch:
    imgpkgBundle:
      # point to your TKG “packages” bundle
      image: projects.registry.vmware.com/tkg/packages-repo:latest
